name: kyc_vision_env
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - pytorch
  - torchvision
  - pytorch-cuda=11.8 #Choose higher or lower depending or machine GPU & CUDA support
  - fastapi=0.111.0
  - uvicorn=0.30.1
  - pydantic=2.8.2
  - opencv
  - numpy=1.26.4
  - insightface
  - easyocr
  - psycopg2
  - streamlit=1.36.0
  - python-multipart
  - pip:
    - ultralytics==8.2.0
